// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCh2_GIzMe-yfUJ8_nX-do4NQ18baHiYQU',
    appId: '1:996901859557:web:c46523ac08738b05d2e40c',
    messagingSenderId: '996901859557',
    projectId: 'vtec-cloudpos',
    authDomain: 'vtec-cloudpos.firebaseapp.com',
    storageBucket: 'vtec-cloudpos.appspot.com',
    measurementId: 'G-REGJ3CQ456',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBB9HDvOi2-J5dtsZ2XIDFciCa-IxbGg4',
    appId: '1:996901859557:android:357aa941dcf0d550d2e40c',
    messagingSenderId: '996901859557',
    projectId: 'vtec-cloudpos',
    storageBucket: 'vtec-cloudpos.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCt4HvNOTo0WIitoveBVUljwPh3iMuOTmU',
    appId: '1:996901859557:ios:51941d3283bf7645d2e40c',
    messagingSenderId: '996901859557',
    projectId: 'vtec-cloudpos',
    storageBucket: 'vtec-cloudpos.appspot.com',
    iosBundleId: 'com.vtec.cloudPos',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCt4HvNOTo0WIitoveBVUljwPh3iMuOTmU',
    appId: '1:996901859557:ios:47af5e62890a6d03d2e40c',
    messagingSenderId: '996901859557',
    projectId: 'vtec-cloudpos',
    storageBucket: 'vtec-cloudpos.appspot.com',
    iosBundleId: 'com.vtec.cloudPos.RunnerTests',
  );
}
